# Generated by Django 5.1 on 2024-09-04 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mall", "0002_product_created_at_product_updated_at"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={
                "ordering": ["-pk"],
                "verbose_name": "상품",
                "verbose_name_plural": "상품",
            },
        ),
    ]
