# Generated by Django 5.1 on 2024-09-14 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mall", "0006_orderpayment"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="order",
            options={
                "ordering": ["-pk"],
                "verbose_name": "주문",
                "verbose_name_plural": "주문",
            },
        ),
    ]
